import {PermissionsAndroid, Platform, StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {colors, fonts} from '../../../res/themes';

export const styles = StyleSheet.create({
  container: {
    paddingTop: Platform.OS === 'ios' ? hp(5) : hp(2),
    flex: 1,
    backgroundColor: colors.background,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    overflow: 'visible',
  },
  footerContainer: {
    backgroundColor: colors.background,
    paddingHorizontal: wp(4),
    paddingBottom: hp(4),
  },
  detailBtn: {
    textAlign: 'center',
    color: colors.darkGray,
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.large,
    lineHeight: 24,
  },
  flexView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  title: {
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.large,
    color: colors.primaryBlack,
  },
  star: {
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.large,
    color: colors.red,
  },
  titleFlex: {
    flexDirection: 'row',
  },
  fileInput: {
    backgroundColor: '#177DB71A',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    marginTop: hp(0.5),
    marginBottom: hp(1),
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.large,
    lineHeight: 32,
  },
  fileName: {
    marginTop: 10,
    fontSize: 14,
    color: colors.primary,
  },
  textInput: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.grey,
    marginTop: hp(0.5),
    marginBottom: hp(1),
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.large,
    lineHeight: 32,
  },
  selectInput: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.grey,
    marginTop: hp(0.5),
    marginBottom: hp(1),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
  },
  selectInputText: {
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.large,
    color: colors.lightGrey,
  },
  halfWidth: {
    flex: 1,
  },
  dropdownModel: {
    height: hp(100),
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  dropdownContainer: {
    position: 'absolute',
    backgroundColor: colors.white,
    paddingVertical: 8,
    paddingHorizontal: 12,
    paddingBottom: hp(10),
    paddingTop: hp(4),
    borderRadius: 8,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  dropdownOption: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: colors.primaryBlack,
  },
  dropdownOptionHover: {
    backgroundColor: colors.lightGrey,
  },
});
