import {Platform, StyleSheet} from 'react-native';
import {colors, fonts} from '../../../res/themes';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    backgroundColor: colors.primary,
  },
  topHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    paddingTop: Platform.OS === 'ios' ? hp(7) : hp(1.5),
  },
  headerText: {
    color: colors.white,
    fontSize: fonts.fontSize['2xl'],
    textAlign: 'center',
    fontFamily: fonts.fontFamily.medium,
  },
  tabContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
    paddingHorizontal: wp(4),
    paddingBottom: hp(5),
  },
  tabButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: colors.primary,
    borderRadius: 71,
  },
  tabButtonText: {
    color: colors.white,
    fontSize: fonts.fontSize.large,
    fontFamily: fonts.fontFamily.primary,
  },
  mainContainer: {
    backgroundColor: colors.background,
    flex: 1,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -hp(3),
    paddingTop: hp(3),
    paddingHorizontal: wp(4),
    paddingBottom: hp(8),
  },
  cardContainer: {
    flexDirection: 'column',
    gap: hp(2),
    marginTop: hp(1),
    marginBottom: hp(10),
  },
  card: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(3),
  },
  calenderContainer: {
    marginBottom: hp(2),
  },
  flexView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2),
  },
  date: {
    color: colors.primaryBlack,
    fontSize: fonts.fontSize.large,
    fontFamily: fonts.fontFamily.medium,
    lineHeight: 24,
  },
  day: {
    color: colors.darkGray,
    fontSize: fonts.fontSize.large,
    fontFamily: fonts.fontFamily.primary,
    lineHeight: 24,
  },
  timeBadge: {
    borderRadius: 4,
    backgroundColor: '#177DB71A',
    width: 50,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeBadgeText: {
    color: colors.primary,
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.medium,
    lineHeight: 22,
    letterSpacing: 0.1,
    textAlign: 'center',
  },
  cardTitle: {
    color: colors.primaryBlack,
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.large,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  cardSubTitle: {
    color: colors.darkGray,
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.medium,
    lineHeight: 22,
    letterSpacing: 0.5,
  },
  avatarWrapper: {
    backgroundColor: colors.primary,
    height: 44,
    width: 44,
    borderRadius: 80,
    padding: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    color: colors.primaryBlack,
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.large,
    lineHeight: 24,
  },
  mail: {
    color: colors.darkGray,
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.normal,
    lineHeight: 18,
    letterSpacing: 0.5,
  },
  iconsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(4),
    marginTop: hp(1.5),
  },
  iconWrapper: {
    height: 40,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.grayTransparent,
    borderRadius: 80,
  },
  birthdayCard: {
    padding: 16,
    borderRadius: 12,
    backgroundColor: colors.white,
    flexDirection: 'row',
    gap: wp(3),
  },
});
