import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {colors, fonts} from '../../../../res/themes';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  mainContainer: {
    marginTop: hp(10),
    backgroundColor: colors.background,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: hp(3),
    paddingHorizontal: wp(4),
    paddingBottom: hp(2),
  },
  userAvatarWrapper: {
    borderWidth: 4,
    borderColor: colors.white,
    borderRadius: 3000,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    color: colors.primaryBlack,
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize['2xl'],
    lineHeight: 32,
    textAlign: 'center',
    paddingBottom: hp(2),
  },
  profileCard: {
    backgroundColor: colors.white,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(2),
  },
  name: {
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize['2xl'],
    color: colors.primaryBlack,
    lineHeight: 32,
    paddingTop: hp(1.5),
    paddingBottom: hp(0.5),
  },
  status: {
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.medium,
    letterSpacing: 0.5,
    lineHeight: 20,
    color: colors.darkGray,
    paddingBottom: hp(1.5),
  },
  iconsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(4),
  },
  iconWrapper: {
    height: 40,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.grayTransparent,
    borderRadius: 80,
  },
  onlineStatus: {
    width: 12,
    height: 12,
    backgroundColor: colors.success,
    borderRadius: 40,
  },
  card: {
    backgroundColor: colors.white,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: 8,
    marginBottom: hp(2),
  },
  businessCard: {
    backgroundColor: colors.white,
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    borderRadius: 8,
    marginBottom: hp(22),
    gap: hp(1),
  },
  flexView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(4),
  },
  businessCardDepartment: {
    color: colors.primary,
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.medium,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  businessCardName: {
    color: colors.primaryBlack,
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.xl,
    lineHeight: 30,
  },
  businessCardPosition: {
    color: colors.darkGray,
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.medium,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.background,
    paddingVertical: hp(1),
    paddingBottom: hp(4),
    width: wp(100),
    paddingHorizontal: wp(4),
  },
  closebtn: {
    textAlign: 'center',
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.xl,
    lineHeight: 26,
    color: colors.darkGray,
  },
  flexBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  title: {
    fontFamily: fonts.fontFamily.medium,
    fontSize: fonts.fontSize.large,
    color: colors.primaryBlack,
  },
  dataContainer: {
    paddingTop: hp(1),
  },
  subtitle: {
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.medium,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: colors.darkGray,
  },
  info: {
    fontFamily: fonts.fontFamily.primary,
    fontSize: fonts.fontSize.medium,
    lineHeight: 22,
    letterSpacing: 0.5,
    color: colors.primaryBlack,
  },
  divider: {
    height: 1,
    backgroundColor: colors.background,
    width: '100%',
    marginVertical: hp(1),
  },
});
